name: diracos2-build-env

channels:
  - conda-forge

dependencies:
  - python >=3.8
  - pip
  # Constructor itself
  - constructor
  - libmambapy
  # Workaround for https://github.com/conda/conda/issues/12219
  - conda 22.9.0
  # For creating release notes and releases
  - packaging
  - requests
  - uritemplate
  - python-dateutil
  - pytz
