name: diracos2-build-env

channels:
  - conda-forge

dependencies:
  - python >=3.8
  - pip
  # Constructor itself
  - constructor
  # For creating release notes and releases
  - packaging
  - requests
  - uritemplate
  - python-dateutil
  - pytz
