name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (optional)'
        required: false
        default: ''
      run_id:
        description: 'GitHub Actions Run ID (optional)'
        required: false
        default: ''

jobs:
  create-release:
    if: github.repository == 'DIRACGrid/DIRACOS2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
        with:
          cache: true
          environments: release
      - name: Create release
        run: |
          pixi run -e release release-notes \
            --token="${{ secrets.GH_TOKEN }}" \
            --run-id="${{ github.event.inputs.run_id }}" \
            --version="${{ github.event.inputs.version }}" \
            --make-release
